@startuml
'https://plantuml.com/class-diagram

Categoria "1"<|--"*" Tipo
Tipo "1"<|--"*" Prenda
ColorRgb "1-2"<|--"*" Prenda
Material "1"<|--"*" Prenda
Trama "1"<|--"*" Prenda

class Prenda {
  Tipo tipo;
  Material material;
  ColorRgb colorPrimario;
  ColorRgb colorSecundario;
  Trama trama;
  getCategoria()
  }

enum Trama {
  LISA,
  ESTAMPA,
  RAYADA,
  LUNARES,
  CUADROS
}

enum Material {
  TELA,
  PLASTICO,
  ACETATO,
  CUERO,
  ALGODON,
  PIQUE
}

enum Categoria {
  PARTE_SUPERIOR,
  PARTE_INFERIOR,
  CALZADO,
  ACCESORIOS
}

enum Tipo {
  GAFAS(CategoriaPrenda.ACCESORIOS),
  REMERA(CategoriaPrenda.PARTE_SUPERIOR),
  PANTALON(CategoriaPrenda.PARTE_INFERIOR),
  ZAPATILLAS(CategoriaPrenda.CALZADO),
  PANIUELO(CategoriaPrenda.ACCESORIOS),
  ZAPATOS(CategoriaPrenda.CALZADO),
  MUSCULOSA(CategoriaPrenda.PARTE_SUPERIOR),
  POLERA(CategoriaPrenda.PARTE_SUPERIOR),
  BOTAS(CategoriaPrenda.CALZADO)
  CategoriaPrenda categoria
  getCategoria()
}

class ColorRgb {
  Integer rojo
  Integer verde
  Integer azul

  getRojo()
  getVerde()
  getAzul()
}


@enduml